### ISSUE TITLE
Getting (400) Bad Request

### ISSUE THREAD

**Issue by whoisearth** [markekraus/PSMSGraph#29]
```
Get-GraphOauthAccessToken : The remote server returned an error: (400) Bad Request.
At line:19 char:33
+ ... $AuthCode | Get-GraphOauthAccessToken -Resource 'https://graph.micros ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WebException
    + FullyQualifiedErrorId : System.Net.WebException,Get-GraphOauthAccessToken
```

Here is my code:

```
Import-Module -name 'PSMSGraph'
#In the credential prompt, provide your application's Client ID as the username and Client Secret as the password
$ClientCredential = Get-Credential
$GraphAppParams = @{
    Name = 'PowerShell Module'
    ClientCredential = $ClientCredential
    RedirectUri = 'https://localhost/'
    Tenant = 'mytenant.onmicrosoft.com'

}
$GraphApp = New-GraphApplication @GraphAppParams
# This will prompt you to log in with your O365/Azure credentials. 
# This is required at least once to authorize the application to act on behalf of your account
# The username and password is not passed back to or stored by PowerShell.
$AuthCode = $GraphApp | Get-GraphOauthAuthorizationCode
Write-Host $AuthCode
# see the following help for what resource to use. 
# get-help Get-GraphOauthAccessToken -Parameter Resource
$GraphAccessToken = $AuthCode | Get-GraphOauthAccessToken -Resource 'https://graph.microsoft.com'
$GraphAccessToken | Export-GraphOAuthAccessToken -Path 'c:\Temp\AccessToken.XML'
```

I've setup my app using the documentation found here:

http://thelazyadministrator.com/2018/03/20/connect-to-the-microsoft-graph-api-with-powershell/

Unsure why it's failing with bad request.

**Comment by whoisearth** [comment]
Here is what I see as my $AuthCode

```
@{AuthCodeCredential=System.Management.Automation.PSCredential; ResultURL=https://localhost/?code=<hugestring>&session_state=<uidvalue>; Application=Guid: <uidvalue> Name: PowerShell Module; AuthCodeBaseURL=https://login.microsoftonline.com/common/
oauth2/authorize; Response=System.Collections.Hashtable; Issued=19/06/2018 11:49:12 AM; Success=System.Management.Automation.PSScriptProperty; Expires=System.Managemen
t.Automation.PSScriptProperty; IsExpired=System.Management.Automation.PSScriptProperty}
```

I've tried both https://graph.microsoft.com and https://graph.windows.net

**Comment by NerdGr8** [comment]
Experiencing the same issue.

**Comment by markekraus** [comment]
I'm not able to reproduce. You'll probably need to dig the $error and get more details. Or, you may need to run something like wireshark or fiddler to capture the entire session.

Make sure you have added the https://localhost/ uri to the application. Also make sure the correct permissions have been added in the dev portal.

You may also need to ensure TLS 1.2 is enabled

```powershell
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor [System.Security.Authentication.SslProtocols]::Tls12
```

**Comment by hanpq** [comment]
Hi, I stumbeled across this exact same issue, and I think I've found an issue related to DayLightSavingTime. In Sweden we just entered summer time and when I now request an Access Token, the "Access Token" type and the ScriptProperties Expires and isExpired does not seem to take DST into account. The Token is considered expired at the same time as the token was issued. This makes the "Update-GraphOauthAccessToken" cmdlet fail with a 400 Bad request error.

I commented out the line "$AccessToken | Update-GraphOauthAccessToken -ErrorAction Stop" from "Invoke-GraphRequest" with the assumption the first token is still valid and then the graph request completed successfully.

An example of the access token object:
$GraphAccessToken
GUID            : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
RequestedDate   : **2019-04-09 13:13:42**
LastRequestDate : 2019-04-09 13:13:42
IsExpired       : True
Expires         : **2019-04-09 13:13:47**
NotBefore       : **2019-04-09 12:08:47**
Scope           : Reports.Read.All
Resource        : https://graph.microsoft.com
IsRefreshable   : True
Application     : Guid: xxxxxxxxxxxxxxxxxxxxxxxxx Name: xxxxxxxxxxxxxxxxxxxxxxx

**Comment by markekraus** [comment]
it's probably related to #26 which is fixed, but I haven't released yet

**Comment by PzKfWg** [comment]
Have the same issue. When prompted, I input my client ID and Client secret, but get an error message from the prompt saying that the authentification failed against a Directory ID... which is not at all the one I am trying to authenticate on! Could it be that it defaults to the AAD my computer is connected to, disregarding the one in the $GraphAppParams?

**Comment by markekraus** [comment]
I have released a new version of the module that incorporates the UTC fix that is the cause of most 400 errors that have been reported. 

https://www.powershellgallery.com/packages/psmsgraph/1.0.27.60
