### ISSUE TITLE
OAuth Access Token is expired at creation

### ISSUE THREAD

**Issue by joelfish** [markekraus/PSMSGraph#31]
I've re-created the app and tried all these steps as a regular user and admin in our tenant and on two different Win 10 workstations.

https://apps.dev.microsoft.com
Redirect URLs: 'https://localhost/'
Delegated Permissions: 'Mail.ReadWrite' and 'User.Read'
Application Permissions: 'Mail.ReadWrite (Admin Only)' and 'User.Read.All (Admin Only)'

My PowerShell:
$AppID = 'AzureAppGUID'
$AppSecret = ConvertTo-SecureString -String 'AzureAppPassword' -AsPlainText -Force
$Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList ($AppID,$AppSecret)
$AppParams = @{
    Name = 'MSGraph'
    ClientCredential = $Credential
    RedirectUri = 'https://localhost/'
    Tenant = 'tenant.onmicrosoft.com'
}
$App = New-GraphApplication @AppParams
$AuthCode = Get-GraphOauthAuthorizationCode -Application $App
$AccessToken = Get-GraphOauthAccessToken -AuthenticationCode $AuthCode

Everything runs fine, but $AccessToken is expired when I create it and I can't use it for anything. Example:
GUID            : TokenGUID
RequestedDate   : 10/3/2018 4:24:50 PM
LastRequestDate : 10/3/2018 4:24:50 PM
IsExpired       : True
Expires         : 10/3/2018 4:24:51 PM
NotBefore       : 10/3/2018 3:19:51 PM
Scope           : {Mail.ReadWrite, User.Read}
Resource        : https://graph.microsoft.com
IsRefreshable   : True
Application     : Guid: AppGUID Name: MSGraph

Interacting with the token by exporting it to a file, importing it from a file, and refreshing has no effect on the expiration.

**Comment by jonwbstr** [comment]
I believe The expiration is set incorrectly, are you getting an error message when using the access token?

**Comment by joelfish** [comment]
Using the token with a cmdlet from the module, returns (401) Unauthorized.
Using the token with Invoke-RestMethod returns InvalidAuthenticationToken.

**Comment by joelfish** [comment]
This appears to be resolved. On the MS Graph call this morning and tested it again. The token is no longer expired at creation. I auto-update modules from PSGallery, so perhaps an update resolved this.

**Comment by markekraus** [comment]
new version released that should fix this: https://www.powershellgallery.com/packages/psmsgraph/1.0.27.60
