### ISSUE TITLE
Invoke-GraphRequest should handle paging

### ISSUE THREAD

**Issue by BatmanAMA** [markekraus/PSMSGraph#40]
Paging is a [well described](https://docs.microsoft.com/en-us/graph/paging?context=graph%2Fapi%2F1.0&view=graph-rest-1.0) core part of graph API and should be part of the Invoke-GraphRequest function. If you're ok with this functionality, I am willing to add it.

**Comment by markekraus** [comment]
I don't think `Invoke-GraphRequest` should handle paging. Currently, the feature functions handle it. Since this works for AAD Grapoh and MS Graph, making IGR page aware is tricky. The knowldge for the correct paging strategy lives with the feature.

**Comment by BatmanAMA** [comment]
Thanks for the feedback, I'll close this then.
